### ISSUE TITLE
Cant light the aether portal with fermium installed

### ISSUE THREAD

**Issue by Sorrekz** [fonnymunkey/FermiumASM#19] opened 2024-07-30 16:24 UTC
it lights up for a sec then breaks itself

**Comment by fonnymunkey** [comment] 2024-07-30 16:35
Duplicate of #13 turn the relevant option off in the normalasm.cfg file

**Closed by fonnymunkey** 2024-07-30 16:35 UTC

**Comment by Sorrekz** [comment] 2024-07-30 16:50
thank you
