### ISSUE TITLE
unkown crash (random crashes with java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by leonpano2006** [fonnymunkey/FermiumASM#6] opened 2024-02-25 21:02 UTC
https://mclo.gs/4LoudRY

https://mclo.gs/qMhgXYO

 java.lang.NoClassDefFoundError does not only happen on enderio, it can also happen on other mod like railcraft and cyclic...

**Comment by fonnymunkey** [comment] 2024-02-25 21:52
I do not see how this is caused by FermiumASM specifically.
You also have other mods erroring with SecurityException similarly in the log file such as DynamicSurroundings, which has reported the same type of [issue](https://github.com/OreCruncher/DynamicSurroundings/issues/570)
The solution given in that issue is adding MixinBootstrap and/or [MixinCompat 0.7-0.8](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility)
FermiumBooter itself on the mod pages already recommends adding these mods as well to prevent these types of issues.
Additionally you renamed FermiumBooter's file, I do not recommend that, it should not be needed and may cause unforeseen issues.

**Comment by fonnymunkey** [comment] 2024-04-21 05:54
Closing as assumed resolved by adding MixinBootstrap/MixinCompat.

**Closed by fonnymunkey** 2024-04-21 05:54 UTC
